spring:
  application:
    name: guabi-backend
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
    store-type: redis
    timeout: 2592000
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shierbi
    username: root
    password: hsp
  # Redis 配置
  redis:
    database: 2
    host: 192.168.174.140
    port: 6379
    timeout: 5000
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
  # rabbitmq 信息
  rabbitmq:
    host: 192.168.174.140
    port: 5672
    password: guest
    username: guest
server:
  address: 0.0.0.0
  port: 8103
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
# 阿里云对象存储
aliyun:
  oss:
    file:
#      endpoint: 
#      keyid: 
#      keysecret:
#      bucketname:

#   access-key: 
#   secret-key: 
#   bucketname: xxxx
## 要使用的模型ID
ai:
  model:
    model-id: 1660100329896673281
# 鱼聪明SDK
yuapi:
  client:
    access-key: 
    secret-key: 
# 支付宝沙箱
pay:
  qrcodeurl: http://localhost:8103/api/alipay/tradeQuery?alipayAccountNo=%s
  alipay:
    APP_ID: 9021000123630043
    APP_PRIVATE_KEY: 
